# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Recipe' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipe
  pod 'Parse', '1.14.2'
  pod 'AFNetworking', '3.0.0'
  pod 'BDBOAuth1Manager', '2.0.0'

end
